version: "3.9"

services: 
    redis:
        image: redis:6.2.3-alpine
        ports: 
            - 6379:6379

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 15672:15672
            